### ISSUE TITLE
No calendar entries created / No event found

### ISSUE THREAD

**Issue by iMiMx** [franc6/ics_calendar#162] opened 2024-09-12 06:50 UTC
Source:: https://nixxo.github.io/calendars/motogp/2024/MotoGP_2024_calendar.ics
Version: 5.0.2

Trying to import the above, just results in no entries (No event found!) and as far as I can see no explicit errors.  The above does work in O365.

Tried:

- rie vs ics parser
- Set days to 30, next event is ~10 days
- Including all day event (shouldn't be required)
- Extending timeout to 60 seconds
- Custom useragent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15"

rie log:

```
2024-09-12 07:40:45.716 DEBUG (MainThread) [custom_components.ics_calendar.calendar] Initializing calendar: MotoGP with URL: https://nixxo.github.io/calendars/motogp/2024/MotoGP_2024_calendar.ics
2024-09-12 07:40:45.723 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: Update was called
2024-09-12 07:40:45.723 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:40:45.724 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:40:45.724 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: Downloading calendar data from: https://nixxo.github.io/calendars/motogp/2024/MotoGP_2024_calendar.ics
2024-09-12 07:40:45.724 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: _download_data start
2024-09-12 07:40:45.892 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: _download_data done
2024-09-12 07:40:45.893 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: download_calendar done
2024-09-12 07:40:45.893 DEBUG (SyncWorker_7) [custom_components.ics_calendar.calendar] MotoGP: Setting calendar content
2024-09-12 07:40:49.772 DEBUG (MainThread) [custom_components.ics_calendar.calendar] MotoGP: async_get_events called; calling internal.
2024-09-12 07:40:49.772 DEBUG (SyncWorker_22) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:40:49.772 DEBUG (SyncWorker_22) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:40:49.772 DEBUG (SyncWorker_22) [custom_components.ics_calendar.calendar] MotoGP: download_calendar skipped download
2024-09-12 07:41:45.721 DEBUG (SyncWorker_41) [custom_components.ics_calendar.calendar] MotoGP: Update was called
2024-09-12 07:41:45.721 DEBUG (SyncWorker_41) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:41:45.722 DEBUG (SyncWorker_41) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:41:45.722 DEBUG (SyncWorker_41) [custom_components.ics_calendar.calendar] MotoGP: download_calendar skipped download
2024-09-12 07:41:45.722 DEBUG (SyncWorker_41) [custom_components.ics_calendar.calendar] MotoGP: No event found!
```

ics log:

```
2024-09-12 07:44:22.760 DEBUG (SyncWorker_24) [custom_components.ics_calendar.calendar] MotoGP: Downloading calendar data from: https://nixxo.github.io/calendars/motogp/2024/MotoGP_2024_calendar.ics
2024-09-12 07:44:22.760 DEBUG (SyncWorker_24) [custom_components.ics_calendar.calendar] MotoGP: _download_data start
2024-09-12 07:44:22.915 DEBUG (SyncWorker_24) [custom_components.ics_calendar.calendar] MotoGP: _download_data done
2024-09-12 07:44:22.916 DEBUG (SyncWorker_24) [custom_components.ics_calendar.calendar] MotoGP: download_calendar done
2024-09-12 07:44:22.917 DEBUG (SyncWorker_24) [custom_components.ics_calendar.calendar] MotoGP: Setting calendar content
2024-09-12 07:44:47.855 DEBUG (MainThread) [custom_components.ics_calendar.calendar] MotoGP: async_get_events called; calling internal.
2024-09-12 07:44:47.855 DEBUG (SyncWorker_49) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:44:47.856 DEBUG (SyncWorker_49) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:44:47.856 DEBUG (SyncWorker_49) [custom_components.ics_calendar.calendar] MotoGP: download_calendar skipped download
2024-09-12 07:45:22.759 DEBUG (SyncWorker_40) [custom_components.ics_calendar.calendar] MotoGP: Update was called
2024-09-12 07:45:22.759 DEBUG (SyncWorker_40) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:45:22.759 DEBUG (SyncWorker_40) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:45:22.759 DEBUG (SyncWorker_40) [custom_components.ics_calendar.calendar] MotoGP: download_calendar skipped download
2024-09-12 07:45:22.759 DEBUG (SyncWorker_40) [custom_components.ics_calendar.calendar] MotoGP: No event found!
2024-09-12 07:46:26.553 DEBUG (MainThread) [custom_components.ics_calendar.calendar] MotoGP: async_get_events called; calling internal.
2024-09-12 07:46:26.553 DEBUG (SyncWorker_26) [custom_components.ics_calendar.calendar] MotoGP: download_calendar start
2024-09-12 07:46:26.553 DEBUG (SyncWorker_26) [custom_components.ics_calendar.calendar] MotoGP: download_calendar lock acquired
2024-09-12 07:46:26.554 DEBUG (SyncWorker_26) [custom_components.ics_calendar.calendar] MotoGP: download_calendar skipped download
```

... not sure why 'download_calendar skipped download' ?

**Comment by franc6** [comment] 2024-09-12 10:18
Duplicate of #146

**Closed as completed by franc6** 2024-09-12 10:18 UTC
Labels: duplicate

**Comment by shalva-an** [comment] 2024-09-25 08:25
@iMiMx Can you enable debug and restart the process of adding the calendar?

See if you have the same issue as me:

My private ics url:
```sh
https://calendar.google.com/calendar/ical/myusername%40gmail.com/private-XyZ12345/basic.ics
```

The logs:
```sh
myCalendarName: Failed to open url(https://calendar.google.com/calendar/ical/myusername%2540gmail.com/private-XyZ12345/basic.ics): Not Found
```

Notice how it replaced `%40` in `myusername%40gmail.com` (for `myusername@gmail.com`) with  `%2540` in `myusername%2540gmail.com` when looking at the debug logs.

Side by side:
```sh
https://calendar.google.com/calendar/ical/myusername%40gmail.com/private-XyZ12345/basic.ics
https://calendar.google.com/calendar/ical/myusername%2540gmail.com/private-XyZ12345/basic.ics
```

@franc6 amazing integration! Surprised it's not part of Home Assistant by default

**Comment by iMiMx** [comment] 2024-09-25 08:31
@shalva-an but my example doesn't have such characters? :)

https://nixxo.github.io/calendars/motogp/2024/MotoGP_2024_calendar.ics

... URL is 'intact' and correct in my logs above.

**Comment by shalva-an** [comment] 2024-09-25 09:19
Hmm, did you have success with another integration? I just added this. It failed at first (parsing recurring events), but then it fixed itself after a couple minutes. 

Might not be related to your issue:
https://github.com/tybritten/ical-sensor-homeassistant

**Comment by Duxlogar** [comment] 2024-10-15 11:04
> @iMiMx Can you enable debug and restart the process of adding the calendar?
> 
> See if you have the same issue as me:
> 
> My private ics url:
> 
> ```shell
> https://calendar.google.com/calendar/ical/myusername%40gmail.com/private-XyZ12345/basic.ics
> ```
> 
> The logs:
> 
> ```shell
> myCalendarName: Failed to open url(https://calendar.google.com/calendar/ical/myusername%2540gmail.com/private-XyZ12345/basic.ics): Not Found
> ```
> 
> Notice how it replaced `%40` in `myusername%40gmail.com` (for `myusername@gmail.com`) with `%2540` in `myusername%2540gmail.com` when looking at the debug logs.
> 
> Side by side:
> 
> ```shell
> https://calendar.google.com/calendar/ical/myusername%40gmail.com/private-XyZ12345/basic.ics
> https://calendar.google.com/calendar/ical/myusername%2540gmail.com/private-XyZ12345/basic.ics
> ```
> 
> @franc6 amazing integration! Surprised it's not part of Home Assistant by default

Same here. It replaces the ...ub8%40gro... by ...ub8%2540gro...

Any idea how to fix it?

**Comment by oliverwoodings** [comment] 2024-10-17 10:25
@Duxlogar @shalva-an @iMiMx I have a very simple workaround: decode the HTML entities in the URL.

It looks like the integration is encoding HTML entities in the calendar URL to try and ensure it is valid URL, but this means it is double-encoding stuff that is already encoded.

In the case of a google calendar, the URL already has `%40` in it, which is a URL-safe representation of `@`. Something in the integration then takes the `%` sign and encodes that, into `%25`.

To work around it, simply replace `%40` in the original URL with `@`, so:

```
https://calendar.google.com/calendar/ical/myusername@gmail.com/private-XyZ12345/basic.ics
```

I just tested it on mine and it works!


cc @franc6 - thank you for the integration, it's really helped me out :)

**Comment by Duxlogar** [comment] 2024-10-18 08:06
> @Duxlogar @shalva-an @iMiMx I have a very simple workaround: decode the HTML entities in the URL.
> 
> It looks like the integration is encoding HTML entities in the calendar URL to try and ensure it is valid URL, but this means it is double-encoding stuff that is already encoded.
> 
> In the case of a google calendar, the URL already has `%40` in it, which is a URL-safe representation of `@`. Something in the integration then takes the `%` sign and encodes that, into `%25`.
> 
> To work around it, simply replace `%40` in the original URL with `@`, so:
> 
> ```
> https://calendar.google.com/calendar/ical/myusername@gmail.com/private-XyZ12345/basic.ics
> ```
> 
> I just tested it on mine and it works!
> 
> cc @franc6 - thank you for the integration, it's really helped me out :)

Easy but effective. That fixed the issue
