### ISSUE TITLE
deprecated functions

### ISSUE THREAD

**Issue by member1980** [franc6/ics_calendar#141] opened 2024-06-21 19:38 UTC
this addin needs an updat, i guess...

Detected that custom integration 'ics_calendar' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/ics_calendar/__init__.py, line 106: hass.helpers.discovery.load_platform(, please report it to the author of the 'ics_calendar' custom integration
Detected that custom integration 'browser_mod' accesses hass.helpers.storage. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from storage directly at custom_components/browser_mod/store.py, line 94: self.store = hass.helpers.storage.Store(STORAGE_VERSION, STORAGE_KEY), please report it to the author of the 'browser_mod' custom integration
Detected that custom integration 'browser_mod' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/browser_mod/mod_view.py, line 24: hass.components.frontend.async_register_built_in_panel(, please report it to the author of the 'browser_mod' custom integration
Detected that custom integration 'thermal_comfort' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/thermal_comfort/__init__.py, line 162: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/dolezsa/thermal_comfort/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by franc6** [comment] 2024-06-22 02:31
This is a duplicate of #134, and will be fixed in the next release.

**Closed as completed by franc6** 2024-06-22 02:31 UTC
Labels: duplicate
