### ISSUE TITLE
Calendars using the default timeout do not work

### ISSUE THREAD

**Issue by wjansenw** [franc6/ics_calendar#205] opened 2024-12-17 12:02 UTC
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version:

Installation Type (put an X between the square brackets for your HA):
[] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[x] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[] x86-64

**Describe the bug**
A clear and concise description of the bug

With the current beta-release, I fail to add new agendas. I have downgraded to .4, and managed to add a new agenda.
Currently not able to provide log files, as I downgraded.

**Comment by franc6** [comment] 2024-12-17 16:15
~~Just FYI, I can reproduce this.  More info: The config flow simply doesn't start.~~

Actually, I can't reproduce it; I had another problem, where the HA UI needed to be reloaded, but didn't reload.  I couldn't add anything at all until I reloaded the UI, even with ics_calendar uninstalled.

I'm going to try more to reproduce the problem now that the other problem is fixed.

**Comment by franc6** [comment] 2024-12-17 19:02
@wjansenw  I still can't reproduce this.  Can you provide some more information on what and how you were adding the new calendars?  Thanks!

**Comment by wjansenw** [comment] 2024-12-18 08:36
When adding a new calendar (ICS parser), I get the following error:
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.ics_calendar.calendar
Bron: custom_components/ics_calendar/calendardata.py:152
integratie: ics Calendar (documentatie, problemen)
Eerst voorgekomen: 09:33:51 (1 gebeurtenissen)
Laatst gelogd: 09:33:51

TEST: Failed to open url!
Traceback (most recent call last):
  File "/config/custom_components/ics_calendar/calendardata.py", line 152, in _download_data
    response = await self._httpx.get(
               ^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 115, in connect_tcp
    with anyio.fail_after(timeout):
         ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.13/site-packages/anyio/_core/_tasks.py", line 111, in fail_after
    deadline = (current_time() + delay) if delay is not None else math.inf
                ~~~~~~~~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'object'
```

**Comment by franc6** [comment] 2024-12-18 12:14
Thank you!  I ran into this, but the calendar is added, so I didn’t realize it was the problem you are seeing. It will be fixed in the next release.

**Closed as completed** 2024-12-18 14:52 UTC
Labels: bug
