### ISSUE TITLE
Detected blocking call to open with args warnings since update to 5.0.4

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [franc6/ics_calendar#183] opened 2024-10-21 12:41 UTC
**Home Assistant Setup**
Please indicate your version of HA and how it is installed.

Version: 2024.10.3

Installation Type (put an X between the square brackets for your HA):
[X] Home Assistant OS
[] Home Assistant OS
[] Home Assistant Supervised
[] Home Assistant Container
[] Home Assistant Core

Hardware platform:
[] ARM
[] x86-64
[X] Odroid N2+

**Describe the bug**
A clear and concise description of the bug

Since update 5.0.4 I get the below warning message in HA logs (this happened as well in HA 2024.9.2 as in HA 2024.10.3)

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 15:23:26 (1 occurrences)
Last logged: 15:23:26

'''Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.12/site-packages/tzdata/zoneinfo/GTB Standard Time'), 'rb') inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 33: self._calendar = Calendar.from_ical(content) (offender: /usr/local/lib/python3.12/zoneinfo/_common.py, line 12: return resources.files(package_name).joinpath(resource_name).open("rb")), please create a bug report at https://github.com/franc6/ics_calendar/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 256, in _handle_refresh self._events.extend(await self._fetcher(self._timespan)) File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 134, in async_get_events active_events = await fetcher(offset_timespan) File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 116, in async_get_events return await entity.async_get_events(hass, timespan.start, end_time) File "/config/custom_components/ics_calendar/calendar.py", line 205, in async_get_events return await self.data.async_get_events(hass, start_date, end_date) File "/config/custom_components/ics_calendar/calendar.py", line 302, in async_get_events self.parser.set_content(self._calendar_data.get()) File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 33, in set_content self._calendar = Calendar.from_ical(content)'''

**Comment by franc6** [comment] 2024-10-21 13:46
@smarthomefamilyverrips Do you mind testing a fix for me?  I think the problem is an extra await that shouldn't be there.  If you can test it, please edit custom_components/ics_calendar/calendar.py, and remove "await" from line 205?  Let me know if the error goes away then, or if something breaks. :). Please don't consider it fixed until after restarting HA.

Thanks!

PS if you post logs again, please be sure to quote the logs (using three ` characters before and after), to help ensure the original formatting is preserved.  It's just easier to read that way. :). Thank you!

**Comment by smarthomefamilyverrips** [comment] 2024-10-21 15:19
> @smarthomefamilyverrips Do you mind testing a fix for me? I think the problem is an extra await that shouldn't be there. If you can test it, please edit custom_components/ics_calendar/calendar.py, and remove "await" from line 205? Let me know if the error goes away then, or if something breaks. :). Please don't consider it fixed until after restarting HA.
> 
> Thanks!
> 
> PS if you post logs again, please be sure to quote the logs (using three ` characters before and after), to help ensure the original formatting is preserved. It's just easier to read that way. :). Thank you!

Sure I will give it a try.

**Comment by smarthomefamilyverrips** [comment] 2024-10-21 15:24
@franc6 just to be sure you mean the "await" in the line "return await ..... " shown on picture attached?


![Screenshot_20241021_182259_Home Assistant](https://github.com/user-attachments/assets/8133058d-d9ae-479b-9bfe-cc1a419ce78a)

**Comment by smarthomefamilyverrips** [comment] 2024-10-21 17:36
@franc6 unless i removed the wrong "await" i get following errors in log directly after start up and this message on my calendar "Could not retrieve events for calendars: ****************"

 ` ` ` Logger: py.warnings
Source: components/recorder/util.py:197
First occurred: 20:30:44 (1 occurrences)
Last logged: 20:30:44

/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/traversals.py:257: RuntimeWarning: coroutine 'ICSCalendarData.async_get_events' was never awaited def visit_clauseelement_list(   ` ` ` 

 ` ` ` Logger: homeassistant.components.automation.ics_calendar_cover
Source: components/calendar/trigger.py:141
integration: Automation (documentation, issues)
First occurred: 20:30:44 (1 occurrences)
Last logged: 20:30:44

Error setting up trigger ICS Calendar Cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 288, in async_attach_trigger
    await listener.async_attach()
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 189, in async_attach
    self._events.extend(await self._fetcher(self._timespan))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 141, in async_get_events
    map(get_trigger_time, active_events), active_events, strict=False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not iterable  ` ` `

 ` ` ` Logger: homeassistant.components.automation.ics_calendar_announcement
Source: components/calendar/trigger.py:141
integration: Automation (documentation, issues)
First occurred: 20:30:44 (1 occurrences)
Last logged: 20:30:44

Error setting up trigger ICS Calendar Announcement
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 288, in async_attach_trigger
    await listener.async_attach()
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 189, in async_attach
    self._events.extend(await self._fetcher(self._timespan))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/calendar/trigger.py", line 141, in async_get_events
    map(get_trigger_time, active_events), active_events, strict=False
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not iterable  ` ` `

 ` ` ` Logger: py.warnings
Source: runner.py:189
First occurred: 20:37:43 (1 occurrences)
Last logged: 20:37:43

/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:491: RuntimeWarning: coroutine 'ICSCalendarData.async_get_events' was never awaited resp, reset = await self.finish_response(request, resp, start_time)  ` ` `

 ` ` ` Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 20:37:42 (2 occurrences)
Last logged: 20:37:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 668, in get
    [
TypeError: 'coroutine' object is not iterable  ` ` `

**Comment by franc6** [comment] 2024-10-21 23:30
Yes, that was the right one. Thank you very much. I need to rework that a little bit, then. The code there is blocking but should not. Thanks again!

**Comment by smarthomefamilyverrips** [comment] 2024-10-22 04:36
@franc6 you are welcome, if you want me to try a potential fix then let me know.

**Comment by franc6** [comment] 2024-12-13 02:02
Not exactly the same, but fixed with #166

**Closed as completed by franc6** 2024-12-13 02:02 UTC
Labels: duplicate

**Comment by gieljnssns** [comment] 2024-12-19 07:18
@franc6 
I've updated to v5.1.0 and I'm seeing the same.
```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 07:56:30 (1 occurrences)
Last logged: 07:56:30

Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.13/site-packages/tzdata/zoneinfo/GMT+0200'), 'rb') inside the event loop by custom integration 'ics_calendar' at custom_components/ics_calendar/parsers/parser_rie.py, line 33: self._calendar = Calendar.from_ical(content) (offender: /usr/local/lib/python3.13/zoneinfo/_common.py, line 12: return resources.files(package_name).joinpath(resource_name).open("rb")), please create a bug report at https://github.com/franc6/ics_calendar/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state await self.async_device_update() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update await self.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 220, in async_update await self.data.async_update() File "/config/custom_components/ics_calendar/calendar.py", line 343, in async_update self.parser.set_content(self._calendar_data.get()) File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 33, in set_content self._calendar = Calendar.from_ical(content)
```

**Comment by franc6** [comment] 2024-12-19 11:49
Note to self: open this as a new issue — it’s very different from the original report (though easy for it to be mistaken). The problem is the parser opening time zone info during parse. Might need to switch back to update instead of async_update?  Not sure why my own logs don’t see this, but maybe due to ics file containing all relevant TZ data?
@mcpfr opened issue #212 for this, too.
