### ISSUE TITLE
Calendar can no longer load

### ISSUE THREAD

**Issue by tardich** [franc6/ics_calendar#113] opened 2023-12-13 02:18 UTC
I'm using ics_calendar 4.1.0 within Home-Assistant 2023.12.0

It has been working without any issue for a while and now, my calendar cannot load anymore.

Here's what I'm getting from Home Assistant logs:

```
2023-12-12 21:11:55.851 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.commun fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/calendar.py", line 175, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/calendar.py", line 264, in update
    self.parser.set_content(self._calendar_data.get())
  File "/config/custom_components/ics_calendar/parsers/parser_rie.py", line 32, in set_content
    self._calendar = Calendar.from_ical(content)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 405, in from_ical
    raise ValueError(cls._format_error(
ValueError: Found no components where exactly one is required: BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Mic [...]
```

Any clue on what can be happening?

**Comment by franc6** [comment] 2023-12-13 10:58
The error indicates a problem with the ics file. It could be a problem downloading the file, or a problem with the file itself. I won’t have time to look into this until after the new year, most likely. In the meantime, you might see if you can download the file manually, and if so, try running it through a validator, like this one: https://icalendar.org/validator.html If it shows errors then the problem is likely with whatever creates the ics file, and not this component. If it says it’s OK and the component is still not loading the file, then something is wrong with the download, either in the component itself, or something with how your HA instance connects.  Whatever is wrong, I suspect the upgrade to HA is just coincidence. I didn’t have trouble with 2023.12.0, and 2023.12.1 seems to be fine, too.
TOM

**Comment by tardich** [comment] 2023-12-13 15:22
May have found out what the issue is.

To start, the ics file is coming straight from Microsoft 365 so I take it that the format should be trustable.

So I downloaded it and ran it through a couple of validators, which detected no issue with the file.

Then, I opened it with a text editor. Something I noticed is the presence of two time zones, for one which TZID line is:

`TZID:tzone://Microsoft/Utc`

And I saw three events related to this time zone (but not new events, they were there for some time already). But anyway, I recreated those events manually, while deleting the previous ones. Then redoing the tests above, showed me that the weird time zone definition was gone, and my calendar started loading again in HA.

If you want, I have the ics file which wasn't working but, obviously, I won't be adding it here. But if you need it to test some stuff, I can send it to you directly.

**Comment by franc6** [comment] 2023-12-13 15:45
Thanks!  That sounds like a poor error message coming from the parser.:( You can send the ics file to franc6 on the HA community forums, or post it here, if you can scrub all the personal data first. I can then work up a bug report for the parser and post a sample that shows the problem.  I’ll create my own sample, not just use yours, so that it will be a minimal example and not have any references to you. I’ll also link the bug report here, so you can see it, too. :)On Dec 13, 2023, at 10:25 AM, Christian Tardif ***@***.***> wrote:﻿
May have found out what the issue is.
To start, the ics file is coming straight from Microsoft 365 so I take it that the format should be trustable.
So I downloaded it and ran it through a couple of validators, which detected no issue with the file.
Then, I opened it with a text editor. Something I noticed is the presence of two time zones, for one which TZID line is:
TZID:tzone://Microsoft/Utc
And I saw three events related to this time zone (but not new events, they were there for some time already). But anyway, I recreated those events manually, while deleting the previous ones. Then redoing the tests above, showed me that the weird time zone definition was gone, and my calendar started loading again in HA.
If you want, I have the ics file which wasn't working but, obviously, I won't be adding it here. But if you need it to test some stuff, I can send it to you directly.

**Comment by franc6** [comment] 2023-12-24 21:47
@tardich Hi!  Just checking to see if you've had a chance to look into sending the file.  I haven't seen anything yet.  Thanks!

**Comment by tardich** [comment] 2024-01-04 13:11
Hello. I tried to send it as personal email through HA community forum, but the file's too big (230kb where only 32kb is accepted).  So I sent a message for you there, waiting on instructions. Cheers!

**Comment by franc6** [comment] 2024-01-04 14:34
Thanks! I have replied to your message now.

**Comment by franc6** [comment] 2024-01-15 16:22
I can't reproduce the problem with the file you sent with either rie or ics parsers.  My guess is there was some strange network error for a while that has since been resolved, but that's a very unsatisfactory guess.  I'm going to close this for now, but please let me know if you ever see this again.  Maybe we'll have better luck reproducing the problem then.

**Closed as completed by franc6** 2024-01-15 16:22 UTC
