### ISSUE TITLE
'ics_calendar' accesses hass.helpers.discovery deprecated from 2024.11 on

### ISSUE THREAD

**Issue by fft1010** [franc6/ics_calendar#144] opened 2024-08-15 11:37 UTC
Hi,
I updated HA to 2024.8.1 this morning and found this warning in the log. As I did not find an issue here, I open this:

`2024-08-15 13:21:36.989 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'ics_calendar' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/ics_calendar/__init__.py, line 106: hass.helpers.discovery.load_platform(, please report it to the author of the 'ics_calendar' custom integration`

Sorry if I overlooked that it is already opened.

thanks
Juergen

**Comment by franc6** [comment] 2024-08-15 12:06
I thought this was reported, but it may have been closed. The problem is fixed, but I’ve not had the time to finish off some other changes to make a release. I think those changes are now complete, but I’m not the most patient of testers (especially with my own code, and “it works” isn’t always good enough) and life is busy. :(. I hope to release it later this month (warning: that’s been my hope since March). TOMOn Aug 15, 2024, at 7:38 AM, fft1010 ***@***.***> wrote:﻿
Hi,
I updated HA to 2024.8.1 this morning and found this warning in the log. As I did not find an issue here, I open this:
2024-08-15 13:21:36.989 WARNING (SyncWorker_3) [homeassistant.helpers.frame] Detected that custom integration 'ics_calendar' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/ics_calendar/__init__.py, line 106: hass.helpers.discovery.load_platform(, please report it to the author of the 'ics_calendar' custom integration
Sorry if I overlooked that it is already opened.
thanks
Juergen

**Comment by franc6** [comment] 2024-09-10 23:13
Fixed in 5.0.0

**Closed as completed by franc6** 2024-09-10 23:13 UTC
