### ISSUE TITLE
RRULE parsing error

### ISSUE THREAD

**Issue by bbrendon** [franc6/ics_calendar#8] opened 2020-02-28 06:02 UTC
On-prem exchange server 2016. I can curl the URL okay but this integration doesn't seem to like it.

```
...
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/grammars.py", line 733, in parse
    return rule()
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/grammars.py", line 782, in parse
    result = self._parse_rhs(ctx, self.exp)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/grammars.py", line 790, in _parse_rhs
    result = ctx._call(ruleinfo)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/contexts.py", line 519, in _call
    result = self._recursive_call(ruleinfo)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/contexts.py", line 548, in _recursive_call
    return self._invoke_rule(ruleinfo, self.memokey)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/contexts.py", line 595, in _invoke_rule
    ruleinfo.impl(self)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/grammars.py", line 296, in parse
    return ctx._token(self.token)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/contexts.py", line 632, in _token
    self._error(token, exclass=FailedToken)
  File "/opt/python-venvs/hass/lib/python3.7/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (1:172) expecting '\r\n' :
DESCRIPTION:\n-------------------------------------------------------\nTicket ...
```

**Comment by franc6** [comment] 2020-02-28 21:59
This might be a dumb question, but can you confirm you're running the latest code?  This looks a lot like issue #5, which was also from an exchange server.  Additionally, the fix for issue #7 should mean you don't see a stack trace like this.

**Comment by bbrendon** [comment] 2020-02-28 22:43
Yup. Latest code. I manually downloaded calendar.py from master and did a diff. No results.

**Comment by franc6** [comment] 2020-02-28 22:56
And you restarted Home Assistant?  If so, please send me a copy of the ICS file in question, so I can look at it.  If you need help in redacting info from it, please let me know, and I can give some guidance on that.  If you don't want to post it even with info redacted, you can contact me more privately on the home assistant community forums as the user franc6.  Thanks!

**Comment by bbrendon** [comment] 2020-02-29 07:28
I sent you a link to the file via the forum messages.

**Comment by franc6** [comment] 2020-03-02 14:33
This is just a quick acknowledgement that I have the file, and can reproduce the problem.  I'll reply again after I know more.  Thanks again!

**Comment by franc6** [comment] 2020-03-02 15:15
It looks like the library I'm using the parse the calendar file can't handle embedded TAB characters, and it should.  If you're running HA on something with a bit more RAM and processing power than an rPi, and you consider the problem to be critical, let me know, and I'll put a work-around in place.  Otherwise, please wait, as I'll be replacing that library over the next few weeks, to address this problem as well as a problem with being unable to use this on most rPis with anything but the smallest and simplest of calendars.  I'm hoping that'll let me fix issue #6, too.  This isn't a top priority project right now, so it's not getting a lot of my time, and I suspect I need to block off at least a whole day to make the necessary changes and test them with my much larger set of test files, now. :)  Thanks again for your patience!

**Comment by bbrendon** [comment] 2020-03-02 17:20
Got it. I can wait. I was trying Calendar integration because they talk about it on the podcast as being useful. Apparently everyone is using google?

**Comment by bbrendon** [comment] 2020-04-09 06:22
@franc6  ping!! Since you've been locked in your house have you made any progress ? :)

**Comment by franc6** [comment] 2020-04-09 11:48
I work from home, anyway, so the restrictions have made no difference to me as far as what I need to work on. I am trying to block out some time on Monday. 

I do understand how the lack of progress can be frustrating, and I do apologize. 

TOM

-- 
Preserve wildlife -- pickle a squirrel!

**Comment by franc6** [comment] 2020-04-30 20:01
There's a similar issue with the pre-release versions that use a different library.

I'm attaching a file that shows the problem.  Note how the DTSTART for the event includes only date information (no time or time zone).  The RRULE for the event has an UNTIL that includes a time.  This mismatch causes problems for dateutil.rrule.  There are a handful of open issues surrounding similar problems in dateutil.rrule.

[issue8.txt](https://github.com/franc6/ics_calendar/files/4560889/issue8.txt)

**Comment by franc6** [comment] 2022-01-04 00:47
This should be fixed when using the rie parser.

**Closed by franc6** 2022-01-04 00:47 UTC
Labels: fixed, not our bug
