### ISSUE TITLE
Plugin won't start

### ISSUE THREAD

**Issue by overload08** [franc6/ics_calendar#105] opened 2023-10-25 07:46 UTC
Hi !

The plugin won't start with HASS 2023.10.5

```
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 24 octobre 2023 à 09:02:48 (1 occurrences)
Last logged: 24 octobre 2023 à 09:02:48

Error during setup of component ics_calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ics_calendar/__init__.py", line 98, in setup
    PLATFORMS[0], DOMAIN, config[DOMAIN], config
                          ~~~~~~^^^^^^^^
KeyError: 'ics_calendar'
```

**Comment by franc6** [comment] 2023-10-25 10:40
This is a duplicate of #102. Please update your configuration.

**Closed as completed by franc6** 2023-10-25 10:40 UTC
Labels: duplicate
