### ISSUE TITLE
edit config.

### ISSUE THREAD

**Issue by GorCed** [franc6/ics_calendar#164] opened 2024-09-12 12:44 UTC
Hi.
I'm running v5.0.2 and try to add prefix on existing entitys.
is that posible and how do you actually do it?

**Comment by franc6** [comment] 2024-09-12 13:45
It's not possible for now (see #161. You'll need to delete the existing calendar and add it again. If you aren't sure of how you want to do it yet, I recommend creating the config for it in YAML, and let it import it. You can probably modify your YAML and let it import it again faster than re-creating it through the UI.

Closing this one as a duplicate of #161.

**Closed as completed by franc6** 2024-09-12 13:45 UTC
Labels: duplicate

**Comment by stefanoklett** [comment] 2024-12-15 21:01
This is really sad.
