### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ASchneiderBR** [franc6/ics_calendar#38] opened 2021-09-21 17:17 UTC
Hello everyone!

First of all, thanks @franc6 for creating this great tool :)

I was wondering: is it possible to change how often the calendar gets updated? After adding a couple of calendars, I can see a huge increase in CPU usage:

![image](https://user-images.githubusercontent.com/25224882/134217269-a0c20b5b-7189-4d12-8818-68a5ffb085c9.png)

The arrow shows when I've disabled all calendars from the integrations menu.

Thanks!

**Comment by franc6** [comment] 2021-09-21 21:37
There's not right now.  You can, however, change the MIN_TIME_BETWEEN_UPDATES value at line 68 of calendar.py for now.  It's currently set to 15 minutes, which means the automated updates shouldn't occur more frequently than that.  If you've got something that's specifically requesting updates, though, that'll happen outside this code.  And my guess is that's what's happening, since that appears to be far more frequently than once every 15 minutes.  If setting it to say, 60 minutes doesn't cause any improvement, please report back here, as that would help confirm the problem, and we might be able to find another way around it.

**Comment by ASchneiderBR** [comment] 2021-09-22 12:03
Hello! Thanks for the reply.

Ok, I've changed to 60 minutes, I'll monitor it and let you know if it helps.

Do you know what other code is might be doing those requests? It looks requests are made in less than 15 mins, indeed...

Also, since I've set it to 60 mins, is it possible to manually fetch new data from the calendars? In case I need to refresh it for some reason.

Thanks!

**Comment by ASchneiderBR** [comment] 2021-09-22 17:03
Hello again.

Unfortunately, changing update rate to 60 minutes did not solved the problem:

![image](https://user-images.githubusercontent.com/25224882/134388713-b6a5a9ad-5ba5-40a2-8eeb-606522a59b1c.png)

Until number 1, HA was running without any calendar enabled. Then I've changed to 60 minutes and gone ahead and updated my HA so it could also restart it. After number 2, HA finished the update and stabilized, I've enabled all calendars, you can see a huge impact in CPU usage again.

Thank you.

**Comment by franc6** [comment] 2021-09-22 17:49
Thanks.  I kinda expected that would be the case.  There are two places in the calendar code which download & parse your calendar. The value I asked you change only affects the code which populates the entities in HA.  AFAIK, all calendar displays within HA (including the new built-in stuff) use the HA REST API to obtain calendar information.  In some unrelated testing (with CalDAV calendars), I noticed that calling the HA REST API will always invoke the other method.  Since this is based on the CalDAV code, I'm pretty sure the same will happen.  Your test pretty much confirms what I suspected.  So if you're displaying calendar entries in the HA interface, that's probably what's doing it.  Or if you have anything else that invokes the REST API for the calendar(s).
I've thought of a possible way around this -- I might be able to serialize the parsed data for say, 2 weeks at a time, and save that into a new entity (along with when it obtained the data, and when the data is for).  Then when these requests from the REST API come in, it can check if the requested data is stored, and if it's current enough, and if so, return data from there. I could make that configurable, so you can choose how far out to store data for (probably only needs to be a little more than what you typically display), and how often to refresh the data.  That should significantly reduce the CPU usage.  As noted in a different entry, I won't be able to get to this until October 2021.  If this is something you think you can do before I get to it, I'll gladly take a PR. :)

**Comment by ASchneiderBR** [comment] 2021-09-22 17:58
Thank you very much for you attention and time :)

I don't think there's any REST calls for calendars...

Sadly I do not have the necessary skills to do it, sorry.

No worries at all, I've just started using calendars in HA, the idea is to create some automations based on those calendars, I have not done anything yet, so there's no rush about it :)

I'll wait for a possible fix, when you have the time.

Thank you very much, again!

**Comment by franc6** [comment] 2021-10-20 02:53
@ASchneiderBR I've just pushed out a new release, 2.1.0, which is an attempt to address this issue.  The major change is to cache both downloaded data for up to 10 minutes, and cache the parsed events for 15 minutes when called through the REST API.  This results in much faster load times when displaying the calendar in the HA UI (after the first time, and only for the next 15 minutes, of course).

I'll make those times configurable later, but I need to understand more about how the HA Throttle class is used, so I don't mess that part up when making it configurable.

For now, please give it a try, and see if this version fixes the problem you're seeing.

**Comment by franc6** [comment] 2022-03-20 23:18
@ASchneiderBR I’m curious, have you looked at this in the more recent versions, particularly with the new rie parser?

**Comment by ASchneiderBR** [comment] 2022-03-21 02:00
Hello! No I had not. I’ll give it a try and let you know. Thanks!

**Comment by ASchneiderBR** [comment] 2022-03-22 18:41
Hello @franc6! I just tested the integration, turned it on actually. Here's the graph after the component was enabled again:

![image](https://user-images.githubusercontent.com/25224882/159552824-07eba934-2171-4d6a-80d5-075a75523986.png)

Goes about 12% of CPU usage every 2 minutos or so.

Thanks!

**Comment by franc6** [comment] 2022-04-19 14:48
This should be fixed with the 2.9.0 release.  If this is still observed, the problem is likely related, but not directly in this component.

**Comment by franc6** [comment] 2022-07-22 23:14
Closing since I've heard nothing new so far.

**Closed by franc6** 2022-07-22 23:14 UTC
Labels: enhancement, fixed
