### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by balajeek** [franc6/ics_calendar#45] opened 2022-02-28 01:48 UTC
Just trying to setup calendar on my HA (latest)
installed ics_calendar latest from hacs.

and added the config like this:
```
calendar:
  - platform: ics_calendar
    calendars:
      - name: "Recycle"
        url: "https://cal.recyclecoach.com/admin/calendars/606-EDI-collection-1497-S12097.ics"
```

The calendar "recycle" shows in the calendar tab, but no entries in there

upon checking the log file i see this error:
2022-02-27 20:38:15 ERROR (MainThread) [custom_components.ics_calendar.calendar] Recycle: Failed to parse ICS!

all this calendar contains are my recycle days, nothing big.
wondering what the problem is.

**Comment by atallo** [comment] 2022-02-28 08:34
Your ICS is invalid:

https://icalendar.org/validator.html?url=https://cal.recyclecoach.com/admin/calendars/606-EDI-collection-1497-S12097.ics

**Comment by balajeek** [comment] 2022-02-28 12:38
This is the only one that my township have it, and it works fine when i subscribe on apple calendar and google calendar.
Do you know why its invalid and what we are looking for?  If you have a sample ics and if you let me know i can try that to make sure HA calendar works.
Thank you.

**Comment by atallo** [comment] 2022-02-28 13:50
https://stackoverflow.com/questions/41795657/invalid-property-tzid-with-php-generated-ics-file

**Comment by atallo** [comment] 2022-02-28 14:07
I don't know. but  https://icalendar.org/validator.html?url=https://cal.recyclecoach.com/admin/calendars/606-EDI-collection-1497-S12097.ics explains the problem in detail.

Quick and easy solution.
* Add to google calendar
* Add to HA, public url calendar in "google calendar".

Google calendar, publish a corrected version

**Comment by franc6** [comment] 2022-02-28 15:03
Thanks for the research for me, but I don't think the problems the validator complains about should be a problem.  The complaints are for missing the VTIMEZONE entries for a rather common timezone designation.  If that is the problem, I should be able to provide a better work-around.  In the mean time, it might be simpler to try setting the "parser" option to "icalevents" or "ics".  Either is unlikely to care about not having the timezone defined inside the ics file.
You can also try asking your township to look into having the calendar published with the relevant timezone entry.  If desired, I can provide the additional information to be placed into the ics file -- it's unlikely to change again any time soon, I hope. :)

**Comment by balajeek** [comment] 2022-02-28 15:12
> 

I already using this integration to get the calendar and adding google into the mix and adding another integration does not sound good to me.  If I can somehow get this calendar to a format that needed and i can make a offline copy and use in this integration.  ics is standard and i am surprise why HA does not support natively.

**Comment by balajeek** [comment] 2022-02-28 15:15
> Thanks for the research for me, but I don't think the problems the validator complains about should be a problem. The complaints are for missing the VTIMEZONE entries for a rather common timezone designation. If that is the problem, I should be able to provide a better work-around. In the mean time, it might be simpler to try setting the "parser" option to "icalevents" or "ics". Either is unlikely to care about not having the timezone defined inside the ics file. You can also try asking your township to look into having the calendar published with the relevant timezone entry. If desired, I can provide the additional information to be placed into the ics file -- it's unlikely to change again any time soon, I hope. :)

My township are pretty bad with citizen enquires and i doubt they will handle it, but I will try it anyway, its worth a shot for long term.  For now please let me know what can i change in the file.  Thanks.

**Comment by franc6** [comment] 2022-02-28 15:19
I highly recommend trying one of the other parser options first.  That will also give me some time to look into providing a work-around within my code, which should be much easier on everyone. :)  I'll be looking into it tomorrow.

**Comment by franc6** [comment] 2022-03-01 16:01
I don't think the calendar is what's wrong.  I was running HA 2022.2.7, and couldn't reproduce the problem.  After updating to 2022.2.9, I see the problem, with other calendars, too.  The parser seems to be happy with the calendar in a non-HA environment.  So, now to go find out what changed, and why it breaks now. :(

**Comment by balajeek** [comment] 2022-03-01 16:19
thanks for the update.

**Comment by franc6** [comment] 2022-03-01 17:10
No, I just wasn't patient enough before, it seems.  I can reproduce a problem before updating HA now, too.  I'd like to be sure I'm seeing the same error, though.  @balajeek Can you check if the home assistant log has the "Failed to parse ICS" error message today? Restart HA and check the log at least 10 minutes after startup has completed.  If it still shows the error, then likely something else is wrong, too.

**Comment by franc6** [comment] 2022-03-01 23:04
@balajeek Please give the new version 2.6.0 a try, I think it might resolve the problem for you.  If it does, please close this issue.  Please also note the new "days" option.  I suspect you'll be happier setting that to a value of 14 or even 30 for this calendar.

**Comment by balajeek** [comment] 2022-03-04 15:11
sorry for the delay, work is hectic.
I tried the new version and it the same, i see the calendar "Recycle" but no entries in them.

here is the error:
`
2022-03-04 09:51:09 ERROR (SyncWorker_2) [custom_components.ics_calendar.calendar] update: Recycle: Failed to parse ICS!
2022-03-04 09:58:56 ERROR (MainThread) [custom_components.ics_calendar.calendar] async_get_events: Recycle: Failed to parse ICS!
2022-03-04 10:07:09 ERROR (SyncWorker_0) [custom_components.ics_calendar.calendar] update: Recycle: Failed to parse ICS!

`

**Comment by franc6** [comment] 2022-03-05 19:26
No problem on the delay. That’s definitely a different problem than what I was fixing. I’ll add some more error output and ask you to report what that shows. It might be Tuesday before I can do that, though.

**Comment by balajeek** [comment] 2022-03-06 00:23
Sure, let me know.

**Comment by franc6** [comment] 2022-03-06 02:51
Please install version 2.6.1.  Please note this won't fix the problem, it will just provide additional output in the logs, since I can't reproduce the problem myself.  I hope it will explain exactly what's wrong.  The output should now include some more information about the type of error, and a listing of calls made to get to the error.  If you don't feel confident you can recognize the whole output from the log, let me know, and we can arrange a private upload of the whole log file (since the log file may contain unrelated information that should not be public).

**Comment by balajeek** [comment] 2022-03-06 13:33
I installed it, let me know where can i send the log file privately. 
Is it the log file that i can download from HA or is it somewhere else?
thank you.

**Comment by balajeek** [comment] 2022-03-06 14:02
my bad, i thought the new version installed but noticed on the log that it couldn't install.

`
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/__init__.py, check the network on the host running Home Assistant
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_rie.py, check the network on the host running Home Assistant
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_ics.py, check the network on the host running Home Assistant
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_icalevents.py, check the network on the host running Home Assistant
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] [__init__.py] was not downloaded.
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] [parser_rie.py] was not downloaded.
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] [parser_ics.py] was not downloaded.
2022-03-06 08:58:04 ERROR (MainThread) [custom_components.hacs] [parser_icalevents.py] was not downloaded.

`

FYI
Also want to mention, every hacs component i installed shows up in hacs page that its installed, but this one ics_calendar never does show up as installed, even though the files are present in the custom_component folder and from log HA is loading them.  then everytime i install again, it does pull the latest version though.  only this time it did not install and gave error.

**Comment by franc6** [comment] 2022-03-06 15:49
I suspect we’ve found the immediate cause of the problem. If it’s not fully installed, parse errors are likely.  I don’t know enough about HACS’ internals to troubleshoot this properly, so a sledge hammer approach is the best I can suggest. :(  Please restart HA, double-check that ics_calendar still shows as not installed. If it doesn’t, delete the custom_components/ics_calendar directory. Remove the repository for ics_calendar from HACS and restart HA again. Then try adding the repository back into HACS, and try installing again.  Save off the HA log file before restarting HA (but after trying to install ics_calendar, and don’t restart HA between adding the repository and installing ics_calendar), and check it for problems.  If, after restarting HA, the install of ics_calendar appears to succeed, then check the logs for errors from it. If it doesn’t appear to be installed, the log you saved a copy of is the one we want to look at, in addition to the new one — there might be clues as to what went wrong there. There’s another bug report that some of the dependencies didn’t get installed when ics_calendar was installed through HACS. I haven’t been able to reproduce that, and while I made some changes, I’m not convinced that was ever fixed. Perhaps you are seeing the same problem, or similar?

**Comment by franc6** [comment] 2022-03-06 15:50
Oh, and thanks for your willingness to help figure out what’s wrong. I really appreciate it.

**Comment by balajeek** [comment] 2022-03-06 23:30
FINALLY IT WORKS, here is what i did following what you wrote:

1. deleted the folder ics_calendar, restarted HA
2. went to hacs->install repositories->select 2.6.1-> install
3. able to see ICS_Calendar with pending restart showing in the hacs UI.
4. checked the log file after 5 min  (pasted below)
5.  Also checked the custom_component folder and i do see ics_calendar folder with many files in it.

```

2022-03-06 18:08:29 WARNING (MainThread) [aiogithubapi] You need to call .set_last_commit to set this property
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/__init__.py, check the network on the host running Home Assistant
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_rie.py, check the network on the host running Home Assistant
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_icalevents.py, check the network on the host running Home Assistant
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] A timeout of 60! seconds was encountered while downloading https://raw.githubusercontent.com/franc6/ics_calendar/2.6.1/custom_components/ics_calendar/parsers/parser_ics.py, check the network on the host running Home Assistant
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] [__init__.py] was not downloaded.
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] [parser_rie.py] was not downloaded.
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] [parser_icalevents.py] was not downloaded.
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] [parser_ics.py] was not downloaded.
2022-03-06 18:09:29 ERROR (MainThread) [custom_components.hacs] local variable 'backup' referenced before assignment

```

6. Restarted HA, checked on hacs and it did show ICS calendar as installed this time.
7. Waited for around 5 min, no log file errors.
8. Checked on calendar tab and oila there it is finally my 'Recycle' calendar with events showing on them.

It did work even though there were errors showing while installing.
I am not sure what made it to work becaz of so many things.  but i have to thanks for your support

**Comment by franc6** [comment] 2022-03-10 17:55
You're welcome, although I admit some disappointment that it started working.  I was really hoping for something I could actually fix.  I suspect this was a problem either due to a poor network connection between your home assistant system and github, or perhaps something related to issue #9.
For now, I'll close this, and the reference above should help me find it again if someone reports something similar.

**Closed as completed by franc6** 2022-03-10 17:55 UTC
Labels: installation

**Comment by franc6** [comment] 2022-03-29 10:13
I suspect the installation problems noted above are the same as https://github.com/hacs/integration/issues/2538
